name: NPM Security Scan

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest

    environment: # Assume that your environment inside repository is named OpenAI
      name: OpenAI
    
    permissions:
      contents: read
      pull-requests: read
      
    steps:
      - name: Checkout Target Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for commit analysis

      - name: Checkout Analysis Tool
        uses: actions/checkout@v4
        with:
          repository: JakeClark-chan/npm_commit_detection
          path: npm_commit_detection
          ref: master

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Setup Environment and Scan
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          # Optional: Add LANGSMITH secrets if needed
          # LANGSMITH_API_KEY: ${{ secrets.LANGSMITH_API_KEY }}
          CONCURRENT_THREADS: ${{ vars.CONCURRENT_THREADS }}
          LLM_MODEL: ${{ vars.LLM_MODEL }}
          LLM_USE_OPENROUTER: ${{ vars.LLM_USE_OPENROUTER }}
          LLM_VERIFICATION_MODEL: ${{ vars.LLM_VERIFICATION_MODEL }}
          
          # Deobfuscation Config
          # Install tool globally and point to it
          DEOBFUSCATOR_TOOL_PATH: "obfuscator-io-deobfuscator"
        run: |
          # 1. Setup uv and venv in the tool directory
          cd npm_commit_detection
          
          echo "Setting up virtual environment..."
          uv venv
          source .venv/bin/activate
          
          echo "Installing Python dependencies..."
          uv pip install -r requirements.txt
          
          # 2. Setup Deobfuscator Tool
          echo "Installing Deobfuscator Tool globally..."
          npm install -g obfuscator-io-deobfuscator
          
          # 3. Run Analysis
          echo "Current directory before running python:"
          pwd
          
          # We need to compare the PR HEAD against the base branch (origin/master)
          # The target repository is at the root of the workspace, so relative path is ../..
          TARGET_REPO_PATH="../"
          
          # Ensure we have the base branch reference for comparison
          git -C "$TARGET_REPO_PATH" fetch origin master:master || true
          
          echo "Starting analysis..."
          # Running with --skip-dynamic for faster CI feedback (static analysis + deobfuscation only)
          # Arguments: <repo_path> <end_tag/hash> <start_tag/hash> <options>
          python main.py "$TARGET_REPO_PATH" HEAD origin/master --skip-dynamic
          
      - name: Check Scan Verdict
        run: |
          # Tìm chuỗi cảnh báo trong tất cả các file report
          # Nếu tìm thấy (-q nghĩa là quiet, tìm thấy trả về 0)
          if grep -r "Verdict: 🚨 MALICIOUS" npm_commit_detection/reports/; then
            echo "❌ CRITICAL: Malicious code detected in the report!"
            # Đây là lệnh quan trọng nhất: Ép GitHub Actions fail
            exit 1
          else
            echo "✅ Scan passed. No malicious verdict found."
          fi
      - name: Upload Analysis Report
        uses: actions/upload-artifact@v4
        if: always() # Upload even if issues are found (exit code 1)
        with:
          name: security-analysis-report
          path: npm_commit_detection/reports/*.md
